language: node_js

node_js:
  - 10

cache:
  directories:
  - $HOME/.npm

services:
  - docker

before_script:
  - make build

script:
  - npm run test:ci
  - npm run report -- -r lcov
  - npm run codecov
  - make test

after_script:
  - make clean

notifications:
  email: false
