name: build

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: tacoss/nodejs@master
        with:
          args: make ci CODECOV_TOKEN=${{ secrets.USE_CODECOV_TOKEN }}
