name: build

on:
  pull_request:
    branches:
    - master

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 23.1.0
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run all tests
        run: make ci CODECOV_TOKEN=${{ secrets.USE_CODECOV_TOKEN }}
